version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=stackover
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5433:5432"