-- liquibase formatted sql

-- changeset Artur:1678885902052-1
CREATE SEQUENCE IF NOT EXISTS answer_seq AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset Artur:1678885902052-2
CREATE SEQUENCE IF NOT EXISTS answer_vote_seq AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset Artur:1678885902052-3
CREATE SEQUENCE IF NOT EXISTS badge_seq AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset Artur:1678885902052-4
CREATE SEQUENCE IF NOT EXISTS chat_seq AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset Artur:1678885902052-5
CREATE SEQUENCE IF NOT EXISTS comment_seq AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset Artur:1678885902052-6
CREATE SEQUENCE IF NOT EXISTS ignore_tag_seq AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset Artur:1678885902052-7
CREATE SEQUENCE IF NOT EXISTS message_seq AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset Artur:1678885902052-8
CREATE SEQUENCE IF NOT EXISTS question_seq AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset Artur:1678885902052-9
CREATE SEQUENCE IF NOT EXISTS question_viewed_seq AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset Artur:1678885902052-10
CREATE SEQUENCE IF NOT EXISTS related_tag_seq AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset Artur:1678885902052-11
CREATE SEQUENCE IF NOT EXISTS reputation_seq AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset Artur:1678885902052-12
CREATE SEQUENCE IF NOT EXISTS role_seq AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset Artur:1678885902052-13
CREATE SEQUENCE IF NOT EXISTS tag_seq AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset Artur:1678885902052-14
CREATE SEQUENCE IF NOT EXISTS tracked_tag_seq AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset Artur:1678885902052-15
CREATE SEQUENCE IF NOT EXISTS user_badges_seq AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset Artur:1678885902052-16
CREATE SEQUENCE IF NOT EXISTS user_favorite_question_seq AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset Artur:1678885902052-17
CREATE SEQUENCE IF NOT EXISTS user_seq AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset Artur:1678885902052-18
CREATE SEQUENCE IF NOT EXISTS vote_question_seq AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset Artur:1678885902052-19
CREATE TABLE answer
(
    id                      BIGINT  NOT NULL,
    persist_date            TIMESTAMP WITHOUT TIME ZONE,
    update_date             TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    question_id             BIGINT  NOT NULL,
    user_id                 BIGINT  NOT NULL,
    html_body               TEXT    NOT NULL,
    is_helpful              BOOLEAN NOT NULL,
    is_deleted              BOOLEAN NOT NULL,
    is_deleted_by_moderator BOOLEAN NOT NULL,
    date_accept_time        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_answer PRIMARY KEY (id)
);

-- changeset Artur:1678885902052-20
CREATE TABLE badges
(
    id                    BIGINT NOT NULL,
    badge_name            VARCHAR(255),
    reputations_for_merit INTEGER,
    description           VARCHAR(255),
    CONSTRAINT pk_badges PRIMARY KEY (id)
);

-- changeset Artur:1678885902052-21
CREATE TABLE bookmarks
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    question_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_bookmarks PRIMARY KEY (id)
);

-- changeset Artur:1678885902052-22
CREATE TABLE chat
(
    id           BIGINT NOT NULL,
    title        VARCHAR(255),
    persist_date TIMESTAMP WITHOUT TIME ZONE,
    chat_type    INTEGER,
    CONSTRAINT pk_chat PRIMARY KEY (id)
);

-- changeset Artur:1678885902052-23
CREATE TABLE comment
(
    id                  BIGINT       NOT NULL,
    text                VARCHAR(255) NOT NULL,
    comment_type        INTEGER      NOT NULL,
    persist_date        TIMESTAMP WITHOUT TIME ZONE,
    last_redaction_date TIMESTAMP WITHOUT TIME ZONE,
    user_id             BIGINT       NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);

-- changeset Artur:1678885902052-24
CREATE TABLE comment_answer
(
    comment_id BIGINT NOT NULL,
    answer_id  BIGINT NOT NULL,
    CONSTRAINT pk_comment_answer PRIMARY KEY (comment_id)
);

-- changeset Artur:1678885902052-25
CREATE TABLE comment_question
(
    comment_id  BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    CONSTRAINT pk_comment_question PRIMARY KEY (comment_id)
);

-- changeset Artur:1678885902052-26
CREATE TABLE group_chat
(
    chat_id BIGINT NOT NULL,
    CONSTRAINT pk_group_chat PRIMARY KEY (chat_id)
);

-- changeset Artur:1678885902052-27
CREATE TABLE groupchat_has_users
(
    chat_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_groupchat_has_users PRIMARY KEY (chat_id, user_id)
);

-- changeset Artur:1678885902052-28
CREATE TABLE message
(
    id                  BIGINT NOT NULL,
    message             TEXT,
    last_redaction_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    persist_date        TIMESTAMP WITHOUT TIME ZONE,
    user_sender_id      BIGINT NOT NULL,
    chat_id             BIGINT NOT NULL,
    CONSTRAINT pk_message PRIMARY KEY (id)
);

-- changeset Artur:1678885902052-29
CREATE TABLE question
(
    id                  BIGINT       NOT NULL,
    title               VARCHAR(255) NOT NULL,
    description         TEXT         NOT NULL,
    persist_date        TIMESTAMP WITHOUT TIME ZONE,
    user_id             BIGINT       NOT NULL,
    last_redaction_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    is_deleted          BOOLEAN,
    CONSTRAINT pk_question PRIMARY KEY (id)
);

-- changeset Artur:1678885902052-30
CREATE TABLE question_has_tag
(
    question_id BIGINT NOT NULL,
    tag_id      BIGINT NOT NULL
);

-- changeset Artur:1678885902052-31
CREATE TABLE question_viewed
(
    id           BIGINT NOT NULL,
    user_id      BIGINT,
    question_id  BIGINT,
    persist_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_question_viewed PRIMARY KEY (id)
);

-- changeset Artur:1678885902052-32
CREATE TABLE related_tag
(
    id        BIGINT NOT NULL,
    main_tag  BIGINT NOT NULL,
    child_tag BIGINT NOT NULL,
    CONSTRAINT pk_related_tag PRIMARY KEY (id)
);

-- changeset Artur:1678885902052-33
CREATE TABLE reputation
(
    id           BIGINT  NOT NULL,
    persist_date TIMESTAMP WITHOUT TIME ZONE,
    author_id    BIGINT  NOT NULL,
    sender_id    BIGINT,
    count        INTEGER,
    type         INTEGER NOT NULL,
    question_id  BIGINT,
    answer_id    BIGINT,
    CONSTRAINT pk_reputation PRIMARY KEY (id)
);

-- changeset Artur:1678885902052-34
CREATE TABLE role
(
    id   BIGINT NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_role PRIMARY KEY (id)
);

-- changeset Artur:1678885902052-35
CREATE TABLE singel_chat
(
    chat_id     BIGINT NOT NULL,
    user_one_id BIGINT NOT NULL,
    use_two_id  BIGINT NOT NULL,
    CONSTRAINT pk_singel_chat PRIMARY KEY (chat_id)
);

-- changeset Artur:1678885902052-36
CREATE TABLE tag
(
    id           BIGINT       NOT NULL,
    name         VARCHAR(255) NOT NULL,
    description  VARCHAR(255),
    persist_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tag PRIMARY KEY (id)
);

-- changeset Artur:1678885902052-37
CREATE TABLE tag_ignore
(
    id             BIGINT NOT NULL,
    ignored_tag_id BIGINT NOT NULL,
    user_id        BIGINT NOT NULL,
    persist_date   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tag_ignore PRIMARY KEY (id)
);

-- changeset Artur:1678885902052-38
CREATE TABLE tag_tracked
(
    id             BIGINT NOT NULL,
    tracked_tag_id BIGINT NOT NULL,
    user_id        BIGINT NOT NULL,
    persist_date   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tag_tracked PRIMARY KEY (id)
);

-- changeset Artur:1678885902052-39
CREATE TABLE user_badges
(
    id        BIGINT NOT NULL,
    ready     BOOLEAN,
    user_id   BIGINT,
    badges_id BIGINT,
    CONSTRAINT pk_user_badges PRIMARY KEY (id)
);

-- changeset Artur:1678885902052-40
CREATE TABLE user_entity
(
    id                  BIGINT NOT NULL,
    email               VARCHAR(255),
    password            VARCHAR(255),
    full_name           VARCHAR(255),
    persist_date        TIMESTAMP WITHOUT TIME ZONE,
    is_enabled          BOOLEAN,
    is_deleted          BOOLEAN,
    city                VARCHAR(255),
    link_site           VARCHAR(255),
    link_github         VARCHAR(255),
    link_vk             VARCHAR(255),
    about               VARCHAR(255),
    image_link          VARCHAR(255),
    last_redaction_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    nickname            VARCHAR(255),
    role_id             BIGINT NOT NULL,
    CONSTRAINT pk_user_entity PRIMARY KEY (id)
);

-- changeset Artur:1678885902052-41
CREATE TABLE user_favorite_question
(
    id           BIGINT NOT NULL,
    persist_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    user_id      BIGINT NOT NULL,
    question_id  BIGINT NOT NULL,
    CONSTRAINT pk_user_favorite_question PRIMARY KEY (id)
);

-- changeset Artur:1678885902052-42
CREATE TABLE votes_on_answers
(
    id           BIGINT NOT NULL,
    user_id      BIGINT NOT NULL,
    answer_id    BIGINT NOT NULL,
    persist_date TIMESTAMP WITHOUT TIME ZONE,
    vote_type    VARCHAR(255),
    CONSTRAINT pk_votes_on_answers PRIMARY KEY (id)
);

-- changeset Artur:1678885902052-43
CREATE TABLE votes_on_questions
(
    id           BIGINT NOT NULL,
    user_id      BIGINT,
    question_id  BIGINT,
    persist_date TIMESTAMP WITHOUT TIME ZONE,
    vote         VARCHAR(255),
    CONSTRAINT pk_votes_on_questions PRIMARY KEY (id)
);

-- changeset Artur:1678885902052-44
ALTER TABLE answer
    ADD CONSTRAINT fk_answer_on_question FOREIGN KEY (question_id) REFERENCES question (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-45
ALTER TABLE answer
    ADD CONSTRAINT fk_answer_on_user FOREIGN KEY (user_id) REFERENCES user_entity (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-46
ALTER TABLE bookmarks
    ADD CONSTRAINT fk_bookmarks_on_question FOREIGN KEY (question_id) REFERENCES question (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-47
ALTER TABLE bookmarks
    ADD CONSTRAINT fk_bookmarks_on_user FOREIGN KEY (user_id) REFERENCES user_entity (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-48
ALTER TABLE comment_answer
    ADD CONSTRAINT fk_comment_answer_on_answer FOREIGN KEY (answer_id) REFERENCES answer (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-49
ALTER TABLE comment_answer
    ADD CONSTRAINT fk_comment_answer_on_comment FOREIGN KEY (comment_id) REFERENCES comment (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-50
ALTER TABLE comment
    ADD CONSTRAINT fk_comment_on_user FOREIGN KEY (user_id) REFERENCES user_entity (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-51
ALTER TABLE comment_question
    ADD CONSTRAINT fk_comment_question_on_comment FOREIGN KEY (comment_id) REFERENCES comment (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-52
ALTER TABLE comment_question
    ADD CONSTRAINT fk_comment_question_on_question FOREIGN KEY (question_id) REFERENCES question (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-53
ALTER TABLE groupchat_has_users
    ADD CONSTRAINT fk_grohasuse_on_group_chat FOREIGN KEY (chat_id) REFERENCES group_chat (chat_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-54
ALTER TABLE groupchat_has_users
    ADD CONSTRAINT fk_grohasuse_on_user FOREIGN KEY (user_id) REFERENCES user_entity (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-55
ALTER TABLE group_chat
    ADD CONSTRAINT fk_group_chat_on_chat FOREIGN KEY (chat_id) REFERENCES chat (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-56
ALTER TABLE message
    ADD CONSTRAINT fk_message_on_chat FOREIGN KEY (chat_id) REFERENCES chat (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-57
ALTER TABLE message
    ADD CONSTRAINT fk_message_on_usersender FOREIGN KEY (user_sender_id) REFERENCES user_entity (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-58
ALTER TABLE question_has_tag
    ADD CONSTRAINT fk_quehastag_on_question FOREIGN KEY (question_id) REFERENCES question (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-59
ALTER TABLE question_has_tag
    ADD CONSTRAINT fk_quehastag_on_tag FOREIGN KEY (tag_id) REFERENCES tag (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-60
ALTER TABLE question
    ADD CONSTRAINT fk_question_on_user FOREIGN KEY (user_id) REFERENCES user_entity (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-61
ALTER TABLE question_viewed
    ADD CONSTRAINT fk_question_viewed_on_question FOREIGN KEY (question_id) REFERENCES question (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-62
ALTER TABLE question_viewed
    ADD CONSTRAINT fk_question_viewed_on_user FOREIGN KEY (user_id) REFERENCES user_entity (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-63
ALTER TABLE related_tag
    ADD CONSTRAINT fk_related_tag_on_child_tag FOREIGN KEY (child_tag) REFERENCES tag (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-64
ALTER TABLE related_tag
    ADD CONSTRAINT fk_related_tag_on_main_tag FOREIGN KEY (main_tag) REFERENCES tag (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-65
ALTER TABLE reputation
    ADD CONSTRAINT fk_reputation_on_answer FOREIGN KEY (answer_id) REFERENCES answer (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-66
ALTER TABLE reputation
    ADD CONSTRAINT fk_reputation_on_author FOREIGN KEY (author_id) REFERENCES user_entity (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-67
ALTER TABLE reputation
    ADD CONSTRAINT fk_reputation_on_question FOREIGN KEY (question_id) REFERENCES question (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-68
ALTER TABLE reputation
    ADD CONSTRAINT fk_reputation_on_sender FOREIGN KEY (sender_id) REFERENCES user_entity (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-69
ALTER TABLE singel_chat
    ADD CONSTRAINT fk_singel_chat_on_chat FOREIGN KEY (chat_id) REFERENCES chat (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-70
ALTER TABLE singel_chat
    ADD CONSTRAINT fk_singel_chat_on_userone FOREIGN KEY (user_one_id) REFERENCES user_entity (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-71
ALTER TABLE singel_chat
    ADD CONSTRAINT fk_singel_chat_on_usetwo FOREIGN KEY (use_two_id) REFERENCES user_entity (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-72
ALTER TABLE tag_ignore
    ADD CONSTRAINT fk_tag_ignore_on_ignoredtag FOREIGN KEY (ignored_tag_id) REFERENCES tag (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-73
ALTER TABLE tag_ignore
    ADD CONSTRAINT fk_tag_ignore_on_user FOREIGN KEY (user_id) REFERENCES user_entity (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-74
ALTER TABLE tag_tracked
    ADD CONSTRAINT fk_tag_tracked_on_trackedtag FOREIGN KEY (tracked_tag_id) REFERENCES tag (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-75
ALTER TABLE tag_tracked
    ADD CONSTRAINT fk_tag_tracked_on_user FOREIGN KEY (user_id) REFERENCES user_entity (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-76
ALTER TABLE user_badges
    ADD CONSTRAINT fk_user_badges_on_badges FOREIGN KEY (badges_id) REFERENCES badges (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-77
ALTER TABLE user_badges
    ADD CONSTRAINT fk_user_badges_on_user FOREIGN KEY (user_id) REFERENCES user_entity (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-78
ALTER TABLE user_entity
    ADD CONSTRAINT fk_user_entity_on_role FOREIGN KEY (role_id) REFERENCES role (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-79
ALTER TABLE user_favorite_question
    ADD CONSTRAINT fk_user_favorite_question_on_question FOREIGN KEY (question_id) REFERENCES question (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-80
ALTER TABLE user_favorite_question
    ADD CONSTRAINT fk_user_favorite_question_on_user FOREIGN KEY (user_id) REFERENCES user_entity (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-81
ALTER TABLE votes_on_answers
    ADD CONSTRAINT fk_votes_on_answers_on_answer FOREIGN KEY (answer_id) REFERENCES answer (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-82
ALTER TABLE votes_on_answers
    ADD CONSTRAINT fk_votes_on_answers_on_user FOREIGN KEY (user_id) REFERENCES user_entity (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-83
ALTER TABLE votes_on_questions
    ADD CONSTRAINT fk_votes_on_questions_on_question FOREIGN KEY (question_id) REFERENCES question (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Artur:1678885902052-84
ALTER TABLE votes_on_questions
    ADD CONSTRAINT fk_votes_on_questions_on_user FOREIGN KEY (user_id) REFERENCES user_entity (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

